### ISSUE TITLE
getCurrentDir() does not work without path before script filename

### ISSUE THREAD

**Issue by gabfl** [gabfl/password-generator-py#1]
```

20:20 gab:~/password-generator-py$ python3 pass.py 
Traceback (most recent call last):
  File "pass.py", line 74, in <module>
    pw = PasswordGenerator();
  File "pass.py", line 20, in __init__
    self.loadDictionary();
  File "pass.py", line 29, in loadDictionary
    with open(self.getCurrentDir() + "data/english.csv") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/english.csv'

20:20 gab:~/password-generator-py$ python3 ./pass.py 
552.Latching_Peckish=Comrade

```

**Comment by gabfl** [comment]
http://stackoverflow.com/questions/12882144/os-path-dirname-file-doesnt-exist
